### ISSUE TITLE
[3369] Portrait playermodel selection can be upside down.

### ISSUE THREAD

**Issue by Henry040** [OldUnreal/UT2004Patches#146]
This applies only when you open game>settings>player menu when playing. 

Look up or down when in-game or as spectator (local or online). Go to player menu.

<img width="450" height="544" alt="Image" src="https://github.com/user-attachments/assets/aa5f257f-3a36-42b9-81c7-9e3624dc8dc7" />

When going back from player menu, the view is pointing upside down(spec) or pointing down (non spec).

**Comment by ukpiglet** [comment]
Same with the weapons! I'll have a look.

<img width="725" height="593" alt="Image" src="https://github.com/user-attachments/assets/4c33d282-d062-413c-8bca-43d57c9c6060" />

**Comment by stijn-volckaert** [comment]
Fixed in preview 5

**Comment by NeonKnightOA** [comment]
> Fixed in preview 5

Where can it be downloaded?

**Comment by ukpiglet** [comment]
Currently only available to the closed testers group.  We're getting a lot closer to general release.

**Comment by NeonKnightOA** [comment]
I hope to release fixed spanish by then. Only one file remains.

Not sure where to upload it, though.

**Comment by Henry040** [comment]
When going back from player menu, the view is pointing upside down(spec) or pointing down (non spec).

Still an issue.

**Comment by ukpiglet** [comment]
Are you certain you're re-testing on 3374p5? I cannot reproduce this on the latest build. I can in earlier builds and in v3369.

Please can you give exact route/instructions on how to reproduce?

On older versions, go to instant action in spec. Look up. Rotate view 90 degrees. Go to settings and spin the player partially round. Go back to spec and look down, and then go back to settings and the spinnydude is the wrong way up and spins round the wrong axis.

<img width="1330" height="835" alt="Image" src="https://github.com/user-attachments/assets/22f46288-353f-426b-acc5-79369e5d6dea" />

On P5 I do the same and:

<img width="1303" height="1038" alt="Image" src="https://github.com/user-attachments/assets/618db633-1e3b-422e-91f3-678258370c89" />

**Comment by Henry040** [comment]
You are right. My bad

**Comment by ukpiglet** [comment]
Yay! I hoped there wasn't more to fix here. Were you still on P4?
